# Generated by Django 5.1 on 2024-11-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticket_checked_in_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checked_in_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Checked-In Count'),
        ),
    ]
