# Generated by Django 5.1 on 2024-11-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_checked_in_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='checked_in',
            new_name='is_checked_in',
        ),
    ]
