# Generated by Django 5.1 on 2024-11-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_booking_is_confirmed_delete_bookingconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
