# Generated by Django 5.1 on 2024-11-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_confirmationtokens_remove_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtokens',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
