# Generated by Django 5.1 on 2024-11-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_confirmationtokens_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmationTokens',
            new_name='ConfirmationToken',
        ),
    ]
