# Generated by Django 5.1 on 2024-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Event Image'),
            preserve_default=False,
        ),
    ]
