# Generated by Django 5.1 on 2024-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_organizer_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtoken',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
