# Generated by Django 5.1 on 2024-12-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_confirmationtoken_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='confirmation_id',
            new_name='booking_id',
        ),
    ]
