# Generated by Django 5.1 on 2024-12-03 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_rename_confirmation_id_ticket_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
