# Generated by Django 5.1 on 2024-12-04 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_confirmationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Check-in Staff', 'Check-in Staff')], default='Organizer', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('email', 'event'), name='unique_booking'),
        ),
    ]
