# Generated by Django 5.1 on 2024-12-08 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_customuser_organizer_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(related_name='staffed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
