# Generated by Django 5.1 on 2024-12-10 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed_tickets',
            field=models.PositiveIntegerField(default=0, verbose_name='Confirmed Tickets'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staffed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
