# Generated by Django 5.1 on 2024-12-10 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_confirmed_tickets_alter_event_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, default='event_images/default.png', null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Starting Time'),
        ),
    ]
