# Generated by Django 5.1 on 2024-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_date_alter_event_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
    ]
