# Generated by Django 5.1 on 2024-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(upload_to='event_images/', verbose_name='Event Image'),
        ),
    ]
