# Generated by Django 5.1 on 2024-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Starting Time'),
        ),
    ]
