# Generated by Django 5.1 on 2024-12-21 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_event_date_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, default='event_images/default.png', upload_to='event_images/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='Starting Time'),
        ),
    ]
